/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppStructuresRouteImport } from './routes/app.structures'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppMeritRouteImport } from './routes/app.merit'
import { Route as AppMatrixRouteImport } from './routes/app.matrix'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppBonusRouteImport } from './routes/app.bonus'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppAllowancesRouteImport } from './routes/app.allowances'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUnauthorizedRouteImport } from './routes/admin.unauthorized'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminTicketsIndexRouteImport } from './routes/admin.tickets.index'
import { Route as AdminEmailsIndexRouteImport } from './routes/admin.emails.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AppEmployeesIdRouteImport } from './routes/app.employees.$id'
import { Route as AppAnalyticsPenetrationRouteImport } from './routes/app.analytics.penetration'
import { Route as AppAnalyticsEquityRouteImport } from './routes/app.analytics.equity'
import { Route as AppAnalyticsCompaRouteImport } from './routes/app.analytics.compa'
import { Route as AdminTicketsIdRouteImport } from './routes/admin.tickets.$id'
import { Route as AdminOrganizationsIdRouteImport } from './routes/admin.organizations.$id'
import { Route as AdminEmailsKeyRouteImport } from './routes/admin.emails.$key'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppStructuresRoute = AppStructuresRouteImport.update({
  id: '/structures',
  path: '/structures',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMeritRoute = AppMeritRouteImport.update({
  id: '/merit',
  path: '/merit',
  getParentRoute: () => AppRoute,
} as any)
const AppMatrixRoute = AppMatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppBonusRoute = AppBonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAllowancesRoute = AppAllowancesRouteImport.update({
  id: '/allowances',
  path: '/allowances',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnauthorizedRoute = AdminUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsIndexRoute = AdminTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTicketsRoute,
} as any)
const AdminEmailsIndexRoute = AdminEmailsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEmailsRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppAnalyticsPenetrationRoute = AppAnalyticsPenetrationRouteImport.update({
  id: '/analytics/penetration',
  path: '/analytics/penetration',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsEquityRoute = AppAnalyticsEquityRouteImport.update({
  id: '/analytics/equity',
  path: '/analytics/equity',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsCompaRoute = AppAnalyticsCompaRouteImport.update({
  id: '/analytics/compa',
  path: '/analytics/compa',
  getParentRoute: () => AppRoute,
} as any)
const AdminTicketsIdRoute = AdminTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTicketsRoute,
} as any)
const AdminOrganizationsIdRoute = AdminOrganizationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrganizationsRoute,
} as any)
const AdminEmailsKeyRoute = AdminEmailsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => AdminEmailsRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/emails': typeof AdminEmailsRouteWithChildren
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/allowances': typeof AppAllowancesRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bonus': typeof AppBonusRoute
  '/app/employees': typeof AppEmployeesRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/matrix': typeof AppMatrixRoute
  '/app/merit': typeof AppMeritRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/structures': typeof AppStructuresRoute
  '/app/support': typeof AppSupportRoute
  '/app/team': typeof AppTeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/emails/$key': typeof AdminEmailsKeyRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/app/analytics/compa': typeof AppAnalyticsCompaRoute
  '/app/analytics/equity': typeof AppAnalyticsEquityRoute
  '/app/analytics/penetration': typeof AppAnalyticsPenetrationRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/emails/': typeof AdminEmailsIndexRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/allowances': typeof AppAllowancesRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bonus': typeof AppBonusRoute
  '/app/employees': typeof AppEmployeesRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/matrix': typeof AppMatrixRoute
  '/app/merit': typeof AppMeritRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/structures': typeof AppStructuresRoute
  '/app/support': typeof AppSupportRoute
  '/app/team': typeof AppTeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/emails/$key': typeof AdminEmailsKeyRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/app/analytics/compa': typeof AppAnalyticsCompaRoute
  '/app/analytics/equity': typeof AppAnalyticsEquityRoute
  '/app/analytics/penetration': typeof AppAnalyticsPenetrationRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/emails': typeof AdminEmailsIndexRoute
  '/admin/tickets': typeof AdminTicketsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/emails': typeof AdminEmailsRouteWithChildren
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/allowances': typeof AppAllowancesRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bonus': typeof AppBonusRoute
  '/app/employees': typeof AppEmployeesRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/matrix': typeof AppMatrixRoute
  '/app/merit': typeof AppMeritRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/structures': typeof AppStructuresRoute
  '/app/support': typeof AppSupportRoute
  '/app/team': typeof AppTeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/emails/$key': typeof AdminEmailsKeyRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/app/analytics/compa': typeof AppAnalyticsCompaRoute
  '/app/analytics/equity': typeof AppAnalyticsEquityRoute
  '/app/analytics/penetration': typeof AppAnalyticsPenetrationRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/emails/': typeof AdminEmailsIndexRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/blog'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/emails'
    | '/admin/messages'
    | '/admin/organizations'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/unauthorized'
    | '/admin/users'
    | '/app/allowances'
    | '/app/approvals'
    | '/app/audit'
    | '/app/bonus'
    | '/app/employees'
    | '/app/help'
    | '/app/matrix'
    | '/app/merit'
    | '/app/onboarding'
    | '/app/reports'
    | '/app/settings'
    | '/app/structures'
    | '/app/support'
    | '/app/team'
    | '/blog/$slug'
    | '/admin/'
    | '/app/'
    | '/admin/blog/$id'
    | '/admin/emails/$key'
    | '/admin/organizations/$id'
    | '/admin/tickets/$id'
    | '/app/analytics/compa'
    | '/app/analytics/equity'
    | '/app/analytics/penetration'
    | '/app/employees/$id'
    | '/admin/blog/'
    | '/admin/emails/'
    | '/admin/tickets/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/messages'
    | '/admin/organizations'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/unauthorized'
    | '/admin/users'
    | '/app/allowances'
    | '/app/approvals'
    | '/app/audit'
    | '/app/bonus'
    | '/app/employees'
    | '/app/help'
    | '/app/matrix'
    | '/app/merit'
    | '/app/onboarding'
    | '/app/reports'
    | '/app/settings'
    | '/app/structures'
    | '/app/support'
    | '/app/team'
    | '/blog/$slug'
    | '/admin'
    | '/app'
    | '/admin/blog/$id'
    | '/admin/emails/$key'
    | '/admin/organizations/$id'
    | '/admin/tickets/$id'
    | '/app/analytics/compa'
    | '/app/analytics/equity'
    | '/app/analytics/penetration'
    | '/app/employees/$id'
    | '/admin/blog'
    | '/admin/emails'
    | '/admin/tickets'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/blog'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/emails'
    | '/admin/messages'
    | '/admin/organizations'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/unauthorized'
    | '/admin/users'
    | '/app/allowances'
    | '/app/approvals'
    | '/app/audit'
    | '/app/bonus'
    | '/app/employees'
    | '/app/help'
    | '/app/matrix'
    | '/app/merit'
    | '/app/onboarding'
    | '/app/reports'
    | '/app/settings'
    | '/app/structures'
    | '/app/support'
    | '/app/team'
    | '/blog/$slug'
    | '/admin/'
    | '/app/'
    | '/admin/blog/$id'
    | '/admin/emails/$key'
    | '/admin/organizations/$id'
    | '/admin/tickets/$id'
    | '/app/analytics/compa'
    | '/app/analytics/equity'
    | '/app/analytics/penetration'
    | '/app/employees/$id'
    | '/admin/blog/'
    | '/admin/emails/'
    | '/admin/tickets/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/structures': {
      id: '/app/structures'
      path: '/structures'
      fullPath: '/app/structures'
      preLoaderRoute: typeof AppStructuresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/merit': {
      id: '/app/merit'
      path: '/merit'
      fullPath: '/app/merit'
      preLoaderRoute: typeof AppMeritRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matrix': {
      id: '/app/matrix'
      path: '/matrix'
      fullPath: '/app/matrix'
      preLoaderRoute: typeof AppMatrixRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bonus': {
      id: '/app/bonus'
      path: '/bonus'
      fullPath: '/app/bonus'
      preLoaderRoute: typeof AppBonusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/allowances': {
      id: '/app/allowances'
      path: '/allowances'
      fullPath: '/app/allowances'
      preLoaderRoute: typeof AppAllowancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unauthorized': {
      id: '/admin/unauthorized'
      path: '/unauthorized'
      fullPath: '/admin/unauthorized'
      preLoaderRoute: typeof AdminUnauthorizedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets/': {
      id: '/admin/tickets/'
      path: '/'
      fullPath: '/admin/tickets/'
      preLoaderRoute: typeof AdminTicketsIndexRouteImport
      parentRoute: typeof AdminTicketsRoute
    }
    '/admin/emails/': {
      id: '/admin/emails/'
      path: '/'
      fullPath: '/admin/emails/'
      preLoaderRoute: typeof AdminEmailsIndexRouteImport
      parentRoute: typeof AdminEmailsRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/app/employees/$id': {
      id: '/app/employees/$id'
      path: '/$id'
      fullPath: '/app/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/app/analytics/penetration': {
      id: '/app/analytics/penetration'
      path: '/analytics/penetration'
      fullPath: '/app/analytics/penetration'
      preLoaderRoute: typeof AppAnalyticsPenetrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics/equity': {
      id: '/app/analytics/equity'
      path: '/analytics/equity'
      fullPath: '/app/analytics/equity'
      preLoaderRoute: typeof AppAnalyticsEquityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics/compa': {
      id: '/app/analytics/compa'
      path: '/analytics/compa'
      fullPath: '/app/analytics/compa'
      preLoaderRoute: typeof AppAnalyticsCompaRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/tickets/$id': {
      id: '/admin/tickets/$id'
      path: '/$id'
      fullPath: '/admin/tickets/$id'
      preLoaderRoute: typeof AdminTicketsIdRouteImport
      parentRoute: typeof AdminTicketsRoute
    }
    '/admin/organizations/$id': {
      id: '/admin/organizations/$id'
      path: '/$id'
      fullPath: '/admin/organizations/$id'
      preLoaderRoute: typeof AdminOrganizationsIdRouteImport
      parentRoute: typeof AdminOrganizationsRoute
    }
    '/admin/emails/$key': {
      id: '/admin/emails/$key'
      path: '/$key'
      fullPath: '/admin/emails/$key'
      preLoaderRoute: typeof AdminEmailsKeyRouteImport
      parentRoute: typeof AdminEmailsRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminEmailsRouteChildren {
  AdminEmailsKeyRoute: typeof AdminEmailsKeyRoute
  AdminEmailsIndexRoute: typeof AdminEmailsIndexRoute
}

const AdminEmailsRouteChildren: AdminEmailsRouteChildren = {
  AdminEmailsKeyRoute: AdminEmailsKeyRoute,
  AdminEmailsIndexRoute: AdminEmailsIndexRoute,
}

const AdminEmailsRouteWithChildren = AdminEmailsRoute._addFileChildren(
  AdminEmailsRouteChildren,
)

interface AdminOrganizationsRouteChildren {
  AdminOrganizationsIdRoute: typeof AdminOrganizationsIdRoute
}

const AdminOrganizationsRouteChildren: AdminOrganizationsRouteChildren = {
  AdminOrganizationsIdRoute: AdminOrganizationsIdRoute,
}

const AdminOrganizationsRouteWithChildren =
  AdminOrganizationsRoute._addFileChildren(AdminOrganizationsRouteChildren)

interface AdminTicketsRouteChildren {
  AdminTicketsIdRoute: typeof AdminTicketsIdRoute
  AdminTicketsIndexRoute: typeof AdminTicketsIndexRoute
}

const AdminTicketsRouteChildren: AdminTicketsRouteChildren = {
  AdminTicketsIdRoute: AdminTicketsIdRoute,
  AdminTicketsIndexRoute: AdminTicketsIndexRoute,
}

const AdminTicketsRouteWithChildren = AdminTicketsRoute._addFileChildren(
  AdminTicketsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminEmailsRoute: typeof AdminEmailsRouteWithChildren
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRouteWithChildren
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTicketsRoute: typeof AdminTicketsRouteWithChildren
  AdminUnauthorizedRoute: typeof AdminUnauthorizedRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminEmailsRoute: AdminEmailsRouteWithChildren,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrganizationsRoute: AdminOrganizationsRouteWithChildren,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTicketsRoute: AdminTicketsRouteWithChildren,
  AdminUnauthorizedRoute: AdminUnauthorizedRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppEmployeesRouteChildren {
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesIdRoute: AppEmployeesIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppRouteChildren {
  AppAllowancesRoute: typeof AppAllowancesRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBonusRoute: typeof AppBonusRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppHelpRoute: typeof AppHelpRoute
  AppMatrixRoute: typeof AppMatrixRoute
  AppMeritRoute: typeof AppMeritRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStructuresRoute: typeof AppStructuresRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAnalyticsCompaRoute: typeof AppAnalyticsCompaRoute
  AppAnalyticsEquityRoute: typeof AppAnalyticsEquityRoute
  AppAnalyticsPenetrationRoute: typeof AppAnalyticsPenetrationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAllowancesRoute: AppAllowancesRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppBonusRoute: AppBonusRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppHelpRoute: AppHelpRoute,
  AppMatrixRoute: AppMatrixRoute,
  AppMeritRoute: AppMeritRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStructuresRoute: AppStructuresRoute,
  AppSupportRoute: AppSupportRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppAnalyticsCompaRoute: AppAnalyticsCompaRoute,
  AppAnalyticsEquityRoute: AppAnalyticsEquityRoute,
  AppAnalyticsPenetrationRoute: AppAnalyticsPenetrationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
